server {
    listen 80 default_server;
    server_name _;

    location /media/ {
        alias /var/openvk/media/;
        autoindex off;
        default_type application/octet-stream;
        add_header Cache-Control "public, max-age=86400";
        add_header X-Content-Type-Options nosniff always;
        add_header Content-Disposition "inline" always;
    }
}
